### ISSUE TITLE
坑，仔细看了才发现，subscribe和puback都还没实现

### ISSUE THREAD

**Issue by z070204z** [wwjwell/im-server#2]
RT

**Comment by wwjwell** [comment]
当时只是一时兴趣，做了这个项目，对MQTT和对IM的认识不够深入，不成体系，随后下掉这个工程，可能会浪费更多的时间。
以后有时间我再写一个经过思考的IM项目

**Comment by z070204z** [comment]
哈哈，太谦虚了，这东西还是很不错，虽然不完整，但还是让我得到一些启发

**Comment by wwjwell** [comment]
Mqtt的Pub 、Sub实现可以参考moquette的实现。
如果基于mqtt做IM需要对topic有比较好的设计。
这两方面系统完全没有做，网上也有一些文章可以参考。
我个人觉得如果只针对于IM，MQTT或许并不是最合适的协议。

**Comment by z070204z** [comment]
哇，这个moquette我看了，感觉就是我想要的东西，感谢老哥
另外有没有好用点的MQTT客户端工具呢？
